#!/usr/bin/env ruby

require 'optparse'
require "yard/method/since"

class YardMethodSince
  include Yard::Method::Since

  def initialize(argv)
    parse_options(argv)
  end

  def generate
    if !@config[:skip_parse]
      generate_databases(@config[:target_directory],
                         from: @config[:from], to: @config[:to])
    end
    compare_databases(@config[:target_directory],
                      github: @config[:github],
                      from: @config[:from], to: @config[:to])
  end

  private

  def parse_options(argv)
    @config = {}
    opt = OptionParser.new
    opt.on('--from VAL') {|v| @config[:from] = v }
    opt.on('--to VAL') {|v| @config[:to] = v }
    opt.on('--github VAL') {|v| @config[:github] = v }
    opt.on('--skip-parsing') { @config[:skip_parse] = true}
    opt.parse!(argv)

    if argv.length > 2
      puts("usage")
      exit(1)
    end

    @config[:target_directory] = argv.first
  end
end

doc = YardMethodSince.new(ARGV)
doc.generate
